package com.sigmastrain.aiplayermod.brain;

public enum DirectiveType {
    MINE,
    GATHER,
    GOTO,
    FOLLOW,
    COMBAT,
    CRAFT,
    SMELT,
    ENCHANT,
    BREW,
    CHANNEL,
    SEND_ITEM,
    BUILD,
    FARM,
    CONTAINER_PLACE,
    CONTAINER_SEARCH,
    CONTAINER_STORE,
    CONTAINER_WITHDRAW,
    TELEPORT,
    IDLE,
    PATROL,
    WIDE_SEARCH,
    AREA_LOOT,
    LOCATE,
    STORE_ALL,
    ME_STORE,
    ME_WITHDRAW,
    CRAFT_REQUEST,
    MEDITATE,
    CULTIVATE,
    SKILL,
    MOUNT_VEHICLE,
    DISMOUNT_VEHICLE,
    DRIVE_VEHICLE,
    REQUISITION
}
