apiVersion: v1
kind: Service
metadata:
  name: aibot-agent
  labels:
    app: aibot-agent
    app.kubernetes.io/part-of: aiplayermod
spec:
  selector:
    app: aibot-agent
  ports:
    - name: http
      port: 5000
      targetPort: 5000
